### ISSUE TITLE
Create User Functionality

### ISSUE THREAD

**Issue by BillyLuisNeedham** [BillyLuisNeedham/yilly-app-ktor#1]
Going to implement as per https://hackernoon.com/hexagonal-architecture-with-kotlin-ktor-and-guice-f1b68fbdf2d9

- [ ] Go through the above, update todos

## Todo
- [ ] [Domain](https://github.com/BillyLuisNeedham/yilly-app-ktor/issues/1#issuecomment-1025223993)
- [ ] Data - in memory data source for users
- [ ] Presentation
- [ ] Data - in memory data source for users refactored to use postgreSQL
- [ ] Additional thoughts have been considered and actioned if required

**Comment by BillyLuisNeedham** [comment]
## Domain
### Todo
- [x] Build out user model
- [ ] Build out Domain module
    - [ ] Decide how best to structure the app (modules vs directories)
- [ ] Build out userRequest DTO
- [ ] Build out create user use case TDD
    - [ ] Returns a User model
